In [4]:
import numpy as np
import re
import pandas as pg
from nltk import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
import sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")


In [6]:
df=pd.read_csv("SMSSpamCollection",sep='\t',names=['labels','message'])
df.head()

<IPython.core.display.Javascript object>

labels                                            message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
lemmitizer=WordNetLemmatizer()
corpus=[]
for i in range(0,len(df.message)):
    review = re.sub('[^a-zA-Z]', ' ', df['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemmitizer.lemmatize(word) for word in review if word not in stopwords.words("english")]
    review=' '.join(review)
    corpus.append(review)

In [8]:
cv=CountVectorizer()
x=cv.fit_transform(corpus).toarray()
y=pd.get_dummies(df['labels'])
y=y.iloc[:,1].values

<IPython.core.display.Javascript object>

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state = 0)
spam_detect_model = MultinomialNB().fit(x_train, y_train)
y_pred=spam_detect_model.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))


[[936  19]
 [  7 153]]
Accuracy Score 0.9766816143497757
Classification report:               precision    recall  f1-score   support

           0       0.99      0.98      0.99       955
           1       0.89      0.96      0.92       160

    accuracy                           0.98      1115
   macro avg       0.94      0.97      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [10]:
linear=LogisticRegression()
knn=KNeighborsClassifier()
dt=DecisionTreeClassifier()
rf=RandomForestClassifier()
xg=XGBClassifier()
Mnb=MultinomialNB()
gbc=GradientBoostingClassifier()
algorithms=[linear,knn,dt,rf,xg,Mnb,gbc,]

for algorithm in algorithms:
    algorithm.fit(x_train,y_train)
    y_pred=algorithm.predict(x_test)
    print("algorithm used"+" "+str(algorithm))
    print(confusion_matrix(y_test,y_pred))



algorithm used LogisticRegression()
[[955   0]
 [ 17 143]]
algorithm used KNeighborsClassifier()
[[955   0]
 [ 91  69]]
algorithm used DecisionTreeClassifier()
[[948   7]
 [ 16 144]]
algorithm used RandomForestClassifier()
[[955   0]
 [ 22 138]]
[15:58:13] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
algorithm used XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_stat

In [12]:
tfidf=TfidfVectorizer()
x=tfidf.fit_transform(corpus).toarray()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state = 0)
linear=LogisticRegression()
knn=KNeighborsClassifier()
dt=DecisionTreeClassifier()
rf=RandomForestClassifier()
xg=XGBClassifier()
Mnb=MultinomialNB()
gbc=GradientBoostingClassifier()
algorithms=[linear,knn,dt,rf,xg,Mnb,gbc,]

for algorithm in algorithms:
    algorithm.fit(x_train,y_train)
    y_pred=algorithm.predict(x_test)
    print("algorithm used"+" "+str(algorithm))
    print(confusion_matrix(y_test,y_pred))



algorithm used LogisticRegression()
[[953   2]
 [ 39 121]]
algorithm used KNeighborsClassifier()
[[955   0]
 [ 98  62]]
algorithm used DecisionTreeClassifier()
[[933  22]
 [ 17 143]]
algorithm used RandomForestClassifier()
[[955   0]
 [ 19 141]]
[16:08:33] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
algorithm used XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_stat

In [13]:
stem =PorterStemmer()
corpus=[]
for i in range(0,len(df.message)):
    review = re.sub('[^a-zA-Z]', ' ', df['message'][i])
    review=review.lower()
    review=review.split()
    review=[stem.stem(word) for word in review if word not in stopwords.words("english")]
    review=' '.join(review)
    corpus.append(review)

In [14]:
cv=CountVectorizer()
x=cv.fit_transform(corpus).toarray()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state = 0)

linear=LogisticRegression()
knn=KNeighborsClassifier()
dt=DecisionTreeClassifier()
rf=RandomForestClassifier()
xg=XGBClassifier()
Mnb=MultinomialNB()
gbc=GradientBoostingClassifier()
algorithms=[linear,knn,dt,rf,xg,Mnb,gbc,]

for algorithm in algorithms:
    algorithm.fit(x_train,y_train)
    y_pred=algorithm.predict(x_test)
    print("algorithm used"+" "+str(algorithm))
    print(confusion_matrix(y_test,y_pred))



algorithm used LogisticRegression()
[[954   1]
 [ 17 143]]
algorithm used KNeighborsClassifier()
[[955   0]
 [ 91  69]]
algorithm used DecisionTreeClassifier()
[[949   6]
 [ 15 145]]
algorithm used RandomForestClassifier()
[[955   0]
 [ 20 140]]
[16:18:07] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
algorithm used XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_stat

In [16]:
tfidf=TfidfVectorizer()
x=tfidf.fit_transform(corpus).toarray()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state = 0)
linear=LogisticRegression()
knn=KNeighborsClassifier()
dt=DecisionTreeClassifier()
rf=RandomForestClassifier()
xg=XGBClassifier()
Mnb=MultinomialNB()
gbc=GradientBoostingClassifier()
algorithms=[linear,knn,dt,rf,xg,Mnb,gbc,]

for algorithm in algorithms:
    algorithm.fit(x_train,y_train)
    y_pred=algorithm.predict(x_test)
    print("algorithm used"+" "+str(algorithm))
    print(confusion_matrix(y_test,y_pred))



algorithm used LogisticRegression()
[[953   2]
 [ 39 121]]
algorithm used KNeighborsClassifier()
[[955   0]
 [ 97  63]]
algorithm used DecisionTreeClassifier()
[[939  16]
 [ 21 139]]
algorithm used RandomForestClassifier()
[[955   0]
 [ 19 141]]
[16:26:01] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
algorithm used XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_stat

## best performing algorithm is XGBC
* both stemming and lemmatixation is giving same accuracy 

# ------------------------------THE END--------------------------------